{% set version = "3.11" %}
{% set ver_major = version.split(".")[0] %}
{% set ver_minor = version.split(".")[1] %}

package:
  name: nsis
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/nsis/files/NSIS%20{{ ver_major }}/{{ version }}/nsis-{{ version }}-src.tar.bz2
    sha256: 19e72062676ebdc67c11dc032ba80b979cdbffd3886c60b04bb442cdd401ff4b
    folder: src
  # Prebuilt third-party plugins (x86 only)
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/BgWorker-20091001.zip
    sha256: be8c5264c796309c465d017b12e12aee62d3c8c20966bbbecb96fb8fabb023ce
    folder: plugins/BgWorker
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/elevate-1.3.0-redist.7z
    sha256: b1b3f070353a0eadee2cea3a575049d10df9763ff24e39313da4cec9455382e1
    folder: plugins/elevate
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/UAC-0.2.4c-20150526.zip
    sha256: 20e3192af5598568887c16d88de59a52c2ce4a26e42c5fb8bee8105dcbbd1760
    folder: plugins/UAC
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/nsis-untgz-5c814c5f2c8a9a14e3a6ddd3e594fcc76db5b86a.zip
    sha256: ae68c41493abbb8800640acdf67a06c63bcceaaf21b539c50c348a20dc4b2803
    folder: plugins/untgz
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/nsis-UnicodePathTest-fa74caef553883f1820049d89e169aff57551796.zip
    sha256: 1a4dc09f0fbb7d6be88835c50a7c95dbd37470c65e29cf676b14e3ad9c4d7494
    folder: plugins/UnicodePathTest
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/AccessControl-1.0.8.3-20210224.zip
    sha256: 9aa60f9c5c023fda2808af216514d8913d2673bc522d944ee771da032a1bdc10
    folder: plugins/access-control

build:
  number: 0
  skip: True   # [not win]
  string: h{{ PKG_HASH }}_log_{{ PKG_BUILDNUM }}  # [nsis_variant == 'log_enabled']
  track_features:
    - nsis_log_enabled  # [nsis_variant == 'log_enabled']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - scons
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - makensis /VERSION

about:
  home: https://nsis.sourceforge.io/Main_Page
  license: zlib-acknowledgement AND bzip2-1.0.6 AND CPL-1.0 AND LGPL-2.1-or-later
  license_file:
    - src/COPYING
    - plugins/UAC/License.txt
    - plugins/untgz/LICENSE.TXT
    - plugins/UnicodePathTest/Readme.txt
  license_family: Other
  summary: A professional open source system to create Windows installers
  description: |
    NSIS (Nullsoft Scriptable Install System) is designed to be as small and
    flexible as possible and is therefore very suitable for internet
    distribution.
  doc_url: https://nsis.sourceforge.io/Docs/
  dev_url: https://github.com/NSIS-Dev

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - patricksnape
