{% set version = "3.08" %}

package:
  name: nsis
  version: {{ version }}

source:
  - url: https://altushost-swe.dl.sourceforge.net/project/nsis/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}.zip
    sha256: 1bb9fc85ee5b220d3869325dbb9d191dfe6537070f641c30fbb275c97051fd0c
    folder: binary
  - url: https://altushost-swe.dl.sourceforge.net/project/nsis/NSIS%20{{ version.split(".")[0] }}/{{ version }}/nsis-{{ version }}-log.zip  # [win and nsis_variant == 'log_enabled']
    # Anaconda verified the upstream-supplied SHA-1 and generated the SHA-256
    sha1: 4fcb221a4dc4719580f201f6399b2035073aeaaa  # [win and nsis_variant == 'log_enabled']
    sha256: 57c190cf636efe8904fb00a81f3d6dac310e361500e1067925283c24fa1ac5ad  # [win and nsis_variant == 'log_enabled']
    folder: binary_with_logging  # [win and nsis_variant == 'log_enabled']
  # Plugins
  - url: https://nsis.sourceforge.io/mediawiki/images/6/62/BgWorker.zip
    sha256: be8c5264c796309c465d017b12e12aee62d3c8c20966bbbecb96fb8fabb023ce
    folder: plugins/BgWorker
  - url: https://code.kliu.org/misc/elevate/elevate-1.3.0-redist.7z
    sha256: b1b3f070353a0eadee2cea3a575049d10df9763ff24e39313da4cec9455382e1
    folder: plugins/elevate
  - url: https://nsis.sourceforge.io/mediawiki/images/8/8f/UAC.zip
    sha256: 20e3192af5598568887c16d88de59a52c2ce4a26e42c5fb8bee8105dcbbd1760
    folder: plugins/UAC
  - url: https://github.com/mingwandroid/nsis-untgz/archive/5c814c5f2c8a9a14e3a6ddd3e594fcc76db5b86a.zip
    sha256: ae68c41493abbb8800640acdf67a06c63bcceaaf21b539c50c348a20dc4b2803
    folder: plugins/untgz
  - url: https://github.com/mingwandroid/nsis-UnicodePathTest/archive/fa74caef553883f1820049d89e169aff57551796.zip
    sha256: 1a4dc09f0fbb7d6be88835c50a7c95dbd37470c65e29cf676b14e3ad9c4d7494
    folder: plugins/UnicodePathTest
  # AccessControl does not provide historical versions as far as I can tell..
  # this is for version v1.0.8.3 - 24th February 2021
  - url: https://nsis.sourceforge.io/mediawiki/images/4/4a/AccessControl.zip
    sha256: 9aa60f9c5c023fda2808af216514d8913d2673bc522d944ee771da032a1bdc10
    folder: plugins/access-control

build:
  number: 0
  skip: True   # [unix]
  string: h{{ PKG_HASH }}_log_{{ PKG_BUILDNUM }}  # [nsis_variant == 'log_enabled']

requirements:

test:
  commands:
    - makensis /VERSION  # [win]

about:
  home: https://nsis.sourceforge.io/Main_Page
  license: zlib-acknowledgement AND bzip2-1.0.6 AND CPL-1.0 AND LGPL-2.1-or-later
  license_file:
    - binary/COPYING
    - plugins/UAC/License.txt
    - plugins/untgz/LICENSE.TXT
    - plugins/UnicodePathTest/Readme.txt
    # plugins/elevate has unknown license
    # plugins/BgWorker has unknown license
  license_family: Other
  summary: A professional open source system to create Windows installers
  description: |
    NSIS (Nullsoft Scriptable Install System) is designed to be as small and
    flexible as possible and is therefore very suitable for internet
    distribution.
  doc_url: https://nsis.sourceforge.io/Docs/
  dev_url: https://github.com/NSIS-Dev

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - patricksnape
