{% set name = "nsis" %}
{% set version = "3.12" %}
{% set ver_major = version.split(".")[0] %}
{% set ver_minor = version.split(".")[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://sourceforge.net/projects/{{ name }}/files/NSIS%20{{ ver_major }}/{{ version }}/{{ name }}-{{ version }}-src.tar.bz2
    sha256: f3ed7a8e4aa2cf4e8cf47d3b563a02559e0cb4934db2662b2f9661b824e2b186
    folder: src
  - url: https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
    sha256: 9a093f68516bd3c1a7abd381377879e40b927212bb629f6aae81016d5853c7d5
    folder: zlib-src  # [win and not arm64]
  # Third-party plugin sources
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/BgWorker-20091001.zip
    sha256: be8c5264c796309c465d017b12e12aee62d3c8c20966bbbecb96fb8fabb023ce
    folder: plugins/BgWorker
  - url: http://code.kliu.org/misc/elevate/elevate-1.3.0-redist.7z
    sha256: b1b3f070353a0eadee2cea3a575049d10df9763ff24e39313da4cec9455382e1
    folder: plugins/elevate
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/UAC-0.2.4c-20150526.zip
    sha256: 20e3192af5598568887c16d88de59a52c2ce4a26e42c5fb8bee8105dcbbd1760
    folder: plugins/UAC
  - git_url: https://github.com/mingwandroid/nsis-untgz.git
    git_rev: 5c814c5f2c8a9a14e3a6ddd3e594fcc76db5b86a
    folder: plugins/untgz
  - git_url: https://github.com/mingwandroid/nsis-UnicodePathTest.git
    git_rev: fa74caef553883f1820049d89e169aff57551796
    folder: plugins/UnicodePathTest
  - url: https://github.com/conda/nsis-mirror/releases/download/v308/AccessControl-1.0.8.3-20210224.zip
    sha256: 9aa60f9c5c023fda2808af216514d8913d2673bc522d944ee771da032a1bdc10
    folder: plugins/access-control

build:
  number: 1
  skip: True   # [not win]
  string: h{{ PKG_HASH }}_log_{{ PKG_BUILDNUM }}  # [nsis_variant == 'log_enabled']
  track_features:
    - nsis_log_enabled  # [nsis_variant == 'log_enabled']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - scons
    - 7zip  # [win]
  host:
    - zlib  # [win and arm64]

test:
  commands:
    - if not exist %PREFIX%\\NSIS\\Bin\\makensis.exe exit 1
    - '%PREFIX%\\NSIS\\Bin\\makensis.exe /VERSION'

about:
  home: https://nsis.sourceforge.io/Main_Page
  license: zlib-acknowledgement AND bzip2-1.0.6 AND CPL-1.0 AND LGPL-2.1-or-later
  license_family: Other
  license_file:
    - src/COPYING
    - plugins/UAC/License.txt
    - plugins/untgz/LICENSE.TXT
    - plugins/UnicodePathTest/Readme.txt
    # plugins/elevate has unknown license
    # plugins/BgWorker has unknown license
  summary: A professional open source system to create Windows installers
  description: |
    NSIS (Nullsoft Scriptable Install System) is designed to be as small and
    flexible as possible and is therefore very suitable for internet
    distribution.
  doc_url: https://nsis.sourceforge.io/Docs
  dev_url: https://github.com/NSIS-Dev

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - patricksnape
